#!/bin/bash

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    exit 1
fi


TheSkyX_Path=$(<"$TheSkyX_Install")
echo "Installing to $TheSkyX_Path"


if [ ! -d "$TheSkyX_Path" ]; then
    echo "Coudln't find TheSkyX application location"
    exit 1
fi

if [ -d "$TheSkyX_Path/Resources/Common/PlugIns64" ]; then
	PLUGINS_DIR="PlugIns64"
else
	PLUGINS_DIR="PlugIns"
fi

echo "Installing in $TheSkyX_Path/Resources/Common/$PLUGINS_DIR/DomePlugIns/"

mkdir -p "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/DomePlugIns/"

cp "/tmp/m1OASYS_X2/domelist m1OASYS.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
if [ "$?" -ne "0" ]; then exit 1; fi
cp "/tmp/m1OASYS_X2/libm1OASYS.dylib" "$TheSkyX_Path/Resources/Common/$PLUGINS_DIR/DomePlugIns/"
if [ "$?" -ne "0" ]; then exit 1; fi

app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/domelist m1OASYS.txt"
	chown $app_owner "$TheSkyX_Path/Resources/Common/PlugIns/$PLUGINS_DIR/libm1OASYS.dylib"
fi

rm -rf /tmp/m1OASYS_X2

